fixed env variable checking

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -28,20 +28,20 @@ checkLocalConfig() {
 
   # Set Default Variables
   [ -z "$ECR_STAGEDIR" ] && ECR_STAGEDIR=/tmp/faig_$ECR_FORTIAIGATE_TAG
-  [ -z "$FAIG_LICENSE_DIR" ] && FAIG_LICENSE_DIR=$HOME/.faig/licenses
+#  [ -z "$FAIG_LICENSE_DIR" ] && FAIG_LICENSE_DIR=$HOME/.faig/licenses
   [ -z "$EKS_ODMD_NG_NODES" ] && EKS_ODMD_NG_NODES=1
   [ -z "$EKS_SPOT_NG_NODES" ] && EKS_SPOT_NG_NODES=1
 
-  if [ -z "$EKS_CLUSTER_NAME" -o -z "$AWS_PROFILE" -o -z "$AWS_REGION" -o -z "$ROUT53_DOMAIN" -o -z "$FAIG_LICENSE_DIR" -o -z "$ECR_FORTIAIGATE_TAG" -o \
+  if [ -z "$EKS_CLUSTER_NAME" -o -z "$AWS_PROFILE" -o -z "$AWS_REGION" -o -z "$FAIG_LICENSE_DIR" -o -z "$ECR_FORTIAIGATE_TAG" -o \
        -z "$ECR_FORTIAIGATE_SOURCE_DIR" -o -z "$ECR_REGION" ]; then
     missing_variables=1
     echo ""
     echo "  MISSING ENVIRONMENT-VARIABES          DESCRIPTION        "
     echo "  -------------------------------------------------------------------------------------------------------------------------------------------------------"
 
-    if [ "${EKS_CLUSTER_NAME}" == "" ]; then
-      echo "  EKS_CLUSTER_NAME                      (required) EKS Cluster Name"
-      echo "                                                   => ie. eks-genai-fortiaigate"
+    if [ "${FAIG_LICENSE_DIR}" == "" ]; then
+      echo "  FAIG_LICENSE_DIR                      (required) EKS Cluster Name"
+      echo "                                                   => ie. FAIG_LICENSE_DIR=$HOME/.faig/licenses"
     fi
 
     if [ "${AWS_PROFILE}" == "" ]; then
@@ -657,8 +657,14 @@ updateAppDNS() {
   # --------------------------------------------------------------------------
   # Get ALB hostname from ingress
   # --------------------------------------------------------------------------
-  ALB_HOSTNAME=$(kubectl -n "$APP_NAMESPACE" get ingress "$APP_INGRESS" \
-    -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/tmp/error.log); ret=$?
+  ALB_HOSTNAME=""
+  while [ -z "$ALB_HOSTNAME" ]; do 
+    ALB_HOSTNAME=$(kubectl -n "$APP_NAMESPACE" get ingress "$APP_INGRESS" \
+      -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/tmp/error.log); ret=$?
+    [ "$ALB_HOSTNAME" != "" ] && break
+
+    sleep 15
+  done
 
   if [ $ret -ne 0 -o -z "$ALB_HOSTNAME" ]; then
     logMessages /tmp/error.log
@@ -1617,6 +1623,33 @@ deleteEKScluster() {
       --output text >/dev/null 2>&1; do
       sleep 20
     done
+
+    # Wait until cluster is deleted
+    while true; do
+      aws eks describe-cluster \
+          --name "$CLUSTER_NAME" \
+          --region "$REGION" \
+          --profile "$PROFILE" >/dev/null 2>&1; ret=$?
+
+aws eks describe-cluster \
+          --name "$CLUSTER_NAME" \
+          --region "$REGION" \
+          --profile "$PROFILE"
+
+aws eks describe-cluster \
+          --name "$CLUSTER_NAME" \
+          --region "$REGION" \
+          --profile "$PROFILE" -o json
+
+echo "XXXXX RET: $ret"
+      [ $ret -ne 0 ] && break
+      sleep 30
+    done
+
+aws eks describe-cluster \
+          --name "$CLUSTER_NAME" \
+          --region "$REGION" \
+          --profile "$PROFILE" -o json
   
     echo " ▪ EKS Cluster ($EKS_CLUSTER_NAME) sucessfuly deleted"
   else
@@ -2140,7 +2173,7 @@ deleteStackAndRepairIfNeeded() {
     fi
 
     if [ "$stt" == "DELETE_IN_PROGRESS" ]; then
-      sleep 15
+      sleep 60
       continue
     fi
 
@@ -2458,10 +2491,10 @@ installFAIGchart() {
       -e "s/XXX_REPOTAG_XXX/$ECR_FORTIAIGATE_TAG/g" \
       -e '/^XXXLICENSESXXX$/{r /tmp/values-licenses.yaml' -e ';d;}' cfg/values-template.yaml > /tmp/values.yaml
 
-  echo " ▪ FortiAIgate Helm Chart Values Files (/tmp/Values.yaml)"
-  echo "   ---------------------------------------------------------------------------------------------------------------------"
-  cat /tmp/values.yaml | sed 's/^/   /g'
-  echo "   ---------------------------------------------------------------------------------------------------------------------"
+  echo " ▪ FortiAIgate Helm Chart Values Files (/tmp/Values.yaml) for rewiew"
+  #echo "   ---------------------------------------------------------------------------------------------------------------------"
+  #cat /tmp/values.yaml | sed 's/^/   /g'
+  #echo "   ---------------------------------------------------------------------------------------------------------------------"
 
   stt=$(helm list -n fortiaigate -o json | jq -r --arg key "fortiaigate" '.[] | select(.name == $key).status')
   if [ "$stt" != "deployed" ]; then 
@@ -3117,14 +3150,15 @@ installOpenWebUI() {
 
   updateAppDNS "open-webui" "webui" "webui.$ROUT53_DOMAIN" "$ROUT53_HOSTED_ZONE_ID"
 
-  host=$(kubectl -n open-webui get ingress webui-ingress -o json | jq -r '.spec.rules[].host') 
+  webui=$(kubectl -n open-webui get ingress webui-ingress -o json | jq -r '.spec.rules[].host') 
+  mgmui=$(kubectl -n fortiaigate get ingress fortiaigate-ingress -o json | jq -r '.status.loadBalancer.ingress[].hostname')
 
   echo ""
   echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-  echo " FortiAIgate Installation Successfully Completed, Access the OpenWeb UI by the following URL:"
-  echo " => https://$host"
+  echo "FortiAIgate Installation Successfully Completed, Access the OpenWeb UI by the following URL:"
+  echo "=> Management Interface...: http://$mgmui"
+  echo "=> User Web UI ...........: https://$webui"
   echo "-------------------------------------------------------------------------------------------------------------------------------------------------------"
-
 }
 
 deleteClassicLoadBalancersInVpc() {
@@ -3176,6 +3210,4 @@ waitForNamespaceDeletion() {
     elapsed=$((elapsed + interval))
   done
 }
-
-
 
